stages:
- publish

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"

pages:
  stage: publish
  image: registry.gitlab.com/lepovirta/keruu:ci
  before_script:
  - mkdir -p public
  script:
  - keruu -config config.yaml -output public/index.html
  artifacts:
    paths:
    - public
