stages:
- build-site
- publish

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

variables:
  NETLIFY_DIRECTORY: public

build-site:
  stage: build-site
  image: registry.gitlab.com/lepovirta/keruu:ci
  before_script:
  - mkdir -p $NETLIFY_DIRECTORY
  script:
  - keruu -config config.yaml -output $NETLIFY_DIRECTORY/index.html
  - cp headers.txt $NETLIFY_DIRECTORY/_headers
  artifacts:
    paths:
    - $NETLIFY_DIRECTORY
    expire_in: 2 days

publish:
  stage: publish
  image: registry.gitlab.com/lepovirta/netlify-deployer:ci
  script:
  - gitlab-deploy-site
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  - if: $CI_MERGE_REQUEST_ID
