aggregation:
  title: Lepo Keruu
  description: Aggregation of interesting posts
  maxPosts: 500
  grouping: weekly

fetch:
  httpTimeout: 30s
  propagateErrors: false

links:
- name: HN
  url: https://hn.algolia.com/?q=$TITLE

feeds:
- name: ane
  url: https://ane.iki.fi/feed.xml
- name: Ben Hoyt
  url: https://benhoyt.com/writings/rss.xml
- name: Brendan Gregg
  url: http://www.brendangregg.com/blog/rss.xml
- name: Daniel Lemire
  url: https://lemire.me/blog/feed/
- name: Digital Grove
  url: https://www.rfleury.com/feed
- name: Dmitry Danilov
  url: https://ddanilov.me/feed.xml
- name: Eli Bendersky
  url: https://eli.thegreenplace.net/feeds/all.atom.xml
- name: Evan Jones
  url: https://www.evanjones.ca/index.rss
- name: Fabien Sanglard
  url: https://fabiensanglard.net/rss.xml
- name: Ginger Bill
  url: https://www.gingerbill.org/article/index.xml
- name: Henrik Warne
  url: https://henrikwarne.com/feed/
- name: High Scalability
  url: http://feeds.feedburner.com/HighScalability
  exclude:
  - "^Sponsored Post:"
- name: Hillel Wayne
  url: https://www.hillelwayne.com/post/index.xml
- name: is this it?
  url: https://isthisit.nz/tags/software-engineering/index.xml
- name: Jason Scott
  url: http://ascii.textfiles.com/feed
- name: Joonas
  url: https://joonas.fi/feed.xml
- name: Juho Snellman
  url: https://www.snellman.net/blog/rss-index.xml
- name: Julia Evans
  url: https://jvns.ca/atom.xml
- name: Karl Zylinski
  url: https://zylinski.se/index.xml
- name: Last Week in AWS
  url: https://www.lastweekinaws.com/feed/
- name: Mathias Lafeldt
  url: https://mathias.blog/rss.xml
- name: matklad
  url: https://matklad.github.io/feed.xml
- name: NRK
  url: https://nrk.neocities.org/rss.xml
- name: null program
  url: https://nullprogram.com/feed/
- name: Philippe Gaultier
  url: https://gaultier.github.io/blog/feed.xml
- name: The Pragmatic Engineer
  url: https://feeds.feedburner.com/ThePragmaticEngineer
- name: Tony Finch
  url: https://dotat.at/@/blog.atom
- name: Viacheslav Biriukov
  url: https://biriukov.dev/index.xml
- name: Vincent Bernat
  url: https://vincent.bernat.ch/en/blog/atom.xml
- name: zwischenzugs
  url: https://zwischenzugs.com/feed/
