aggregation:
  title: Lepo Keruu
  description: Aggregation of interesting posts
  maxPosts: 500
  grouping: weekly

fetch:
  httpTimeout: 30s
  propagateErrors: false

links:
- name: HN
  url: https://hn.algolia.com/?q=$TITLE

feeds:
# People
- name: ane
  url: https://ane.iki.fi/feed.xml
- name: Ben Hoyt
  url: https://benhoyt.com/writings/rss.xml
- name: Brendan Gregg
  url: http://www.brendangregg.com/blog/rss.xml
- name: computer.rip
  url: https://computer.rip/rss.xml
- name: Digital Grove
  url: https://www.rfleury.com/feed
- name: Edward Snowden
  url: https://edwardsnowden.substack.com/feed
- name: Evan Jones
  url: https://www.evanjones.ca/index.rss
- name: Fabien Sanglard
  url: https://fabiensanglard.net/rss.xml
- name: Felix Terkhorn
  url: https://dev.to/feed/terkwood
- name: Henrik Warne
  url: https://henrikwarne.com/feed/
- name: Hillel Wayne
  url: https://www.hillelwayne.com/post/index.xml
- name: is this it?
  url: https://isthisit.nz/tags/software-engineering/index.xml
- name: Jason Scott
  url: http://ascii.textfiles.com/feed
- name: Joonas
  url: https://joonas.fi/feed.xml
- name: Juho Snellman
  url: https://www.snellman.net/blog/rss-index.xml
- name: Julia Evans
  url: https://jvns.ca/atom.xml
- name: matklad
  url: https://matklad.github.io/feed.xml
- name: null program
  url: https://nullprogram.com/feed/
- name: Pekka Enberg
  url: http://penberg.org/index.xml
- name: The Pragmatic Engineer
  url: https://feeds.feedburner.com/ThePragmaticEngineer
- name: Sandor Dargo
  url: https://www.sandordargo.com/feed.xml
- name: SecureCloudBlog
  url: https://securecloud.blog/feed/
- name: The Sharp End
  url: https://sharpend.io/feed.xml
- name: Topi Kettunen
  url: https://topikettunen.com/blog/feed.xml
- name: Vincent Bernat
  url: https://vincent.bernat.ch/en/blog/atom.xml
- name: zwischenzugs
  url: https://zwischenzugs.com/feed/

# Infrastructure/ops
- name: High Scalability
  url: http://feeds.feedburner.com/HighScalability
  exclude:
  - "^Sponsored Post:"
- name: Last Week in AWS
  url: https://www.lastweekinaws.com/feed/
- name: Postgres Weekly
  url: https://postgresweekly.com/rss/
