name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Keruu
        uses: jpallari/keruu@main
        with:
          config-path: config.yaml
          output-path: index.html
      - name: Upload Keruu output
        uses: actions/upload-artifact@v4
        with:
          name: keruu.html
          path: index.html
          retention-days: 7

